// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drivermsg.proto

package amber.proto;

public final class AmberProto {
  private AmberProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum DeviceType
      implements com.google.protobuf.ProtocolMessageEnum {
    NINEDOF(0, 1),
    ROBOCLAW(1, 2),
    STARGAZER(2, 3),
    ;
    
    public static final int NINEDOF_VALUE = 1;
    public static final int ROBOCLAW_VALUE = 2;
    public static final int STARGAZER_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static DeviceType valueOf(int value) {
      switch (value) {
        case 1: return NINEDOF;
        case 2: return ROBOCLAW;
        case 3: return STARGAZER;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeviceType>() {
            public DeviceType findValueByNumber(int number) {
              return DeviceType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return amber.proto.AmberProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final DeviceType[] VALUES = {
      NINEDOF, ROBOCLAW, STARGAZER, 
    };
    
    public static DeviceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private DeviceType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:amber.DeviceType)
  }
  
  public interface DriverHdrOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 deviceType = 1;
    boolean hasDeviceType();
    int getDeviceType();
    
    // optional int32 deviceID = 2;
    boolean hasDeviceID();
    int getDeviceID();
    
    // repeated int32 clientIDs = 3 [packed = true];
    java.util.List<java.lang.Integer> getClientIDsList();
    int getClientIDsCount();
    int getClientIDs(int index);
  }
  public static final class DriverHdr extends
      com.google.protobuf.GeneratedMessage
      implements DriverHdrOrBuilder {
    // Use DriverHdr.newBuilder() to construct.
    private DriverHdr(Builder builder) {
      super(builder);
    }
    private DriverHdr(boolean noInit) {}
    
    private static final DriverHdr defaultInstance;
    public static DriverHdr getDefaultInstance() {
      return defaultInstance;
    }
    
    public DriverHdr getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return amber.proto.AmberProto.internal_static_amber_DriverHdr_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return amber.proto.AmberProto.internal_static_amber_DriverHdr_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 deviceType = 1;
    public static final int DEVICETYPE_FIELD_NUMBER = 1;
    private int deviceType_;
    public boolean hasDeviceType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getDeviceType() {
      return deviceType_;
    }
    
    // optional int32 deviceID = 2;
    public static final int DEVICEID_FIELD_NUMBER = 2;
    private int deviceID_;
    public boolean hasDeviceID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getDeviceID() {
      return deviceID_;
    }
    
    // repeated int32 clientIDs = 3 [packed = true];
    public static final int CLIENTIDS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> clientIDs_;
    public java.util.List<java.lang.Integer>
        getClientIDsList() {
      return clientIDs_;
    }
    public int getClientIDsCount() {
      return clientIDs_.size();
    }
    public int getClientIDs(int index) {
      return clientIDs_.get(index);
    }
    private int clientIDsMemoizedSerializedSize = -1;
    
    private void initFields() {
      deviceType_ = 0;
      deviceID_ = 0;
      clientIDs_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, deviceType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, deviceID_);
      }
      if (getClientIDsList().size() > 0) {
        output.writeRawVarint32(26);
        output.writeRawVarint32(clientIDsMemoizedSerializedSize);
      }
      for (int i = 0; i < clientIDs_.size(); i++) {
        output.writeInt32NoTag(clientIDs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deviceType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, deviceID_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < clientIDs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(clientIDs_.get(i));
        }
        size += dataSize;
        if (!getClientIDsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        clientIDsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static amber.proto.AmberProto.DriverHdr parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static amber.proto.AmberProto.DriverHdr parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static amber.proto.AmberProto.DriverHdr parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static amber.proto.AmberProto.DriverHdr parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static amber.proto.AmberProto.DriverHdr parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static amber.proto.AmberProto.DriverHdr parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static amber.proto.AmberProto.DriverHdr parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static amber.proto.AmberProto.DriverHdr parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static amber.proto.AmberProto.DriverHdr parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static amber.proto.AmberProto.DriverHdr parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(amber.proto.AmberProto.DriverHdr prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements amber.proto.AmberProto.DriverHdrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return amber.proto.AmberProto.internal_static_amber_DriverHdr_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return amber.proto.AmberProto.internal_static_amber_DriverHdr_fieldAccessorTable;
      }
      
      // Construct using amber.proto.AmberProto.DriverHdr.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        deviceType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        clientIDs_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return amber.proto.AmberProto.DriverHdr.getDescriptor();
      }
      
      public amber.proto.AmberProto.DriverHdr getDefaultInstanceForType() {
        return amber.proto.AmberProto.DriverHdr.getDefaultInstance();
      }
      
      public amber.proto.AmberProto.DriverHdr build() {
        amber.proto.AmberProto.DriverHdr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private amber.proto.AmberProto.DriverHdr buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        amber.proto.AmberProto.DriverHdr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public amber.proto.AmberProto.DriverHdr buildPartial() {
        amber.proto.AmberProto.DriverHdr result = new amber.proto.AmberProto.DriverHdr(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceType_ = deviceType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceID_ = deviceID_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          clientIDs_ = java.util.Collections.unmodifiableList(clientIDs_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.clientIDs_ = clientIDs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof amber.proto.AmberProto.DriverHdr) {
          return mergeFrom((amber.proto.AmberProto.DriverHdr)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(amber.proto.AmberProto.DriverHdr other) {
        if (other == amber.proto.AmberProto.DriverHdr.getDefaultInstance()) return this;
        if (other.hasDeviceType()) {
          setDeviceType(other.getDeviceType());
        }
        if (other.hasDeviceID()) {
          setDeviceID(other.getDeviceID());
        }
        if (!other.clientIDs_.isEmpty()) {
          if (clientIDs_.isEmpty()) {
            clientIDs_ = other.clientIDs_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureClientIDsIsMutable();
            clientIDs_.addAll(other.clientIDs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deviceType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              deviceID_ = input.readInt32();
              break;
            }
            case 24: {
              ensureClientIDsIsMutable();
              clientIDs_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addClientIDs(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 deviceType = 1;
      private int deviceType_ ;
      public boolean hasDeviceType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getDeviceType() {
        return deviceType_;
      }
      public Builder setDeviceType(int value) {
        bitField0_ |= 0x00000001;
        deviceType_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceType_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 deviceID = 2;
      private int deviceID_ ;
      public boolean hasDeviceID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getDeviceID() {
        return deviceID_;
      }
      public Builder setDeviceID(int value) {
        bitField0_ |= 0x00000002;
        deviceID_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceID_ = 0;
        onChanged();
        return this;
      }
      
      // repeated int32 clientIDs = 3 [packed = true];
      private java.util.List<java.lang.Integer> clientIDs_ = java.util.Collections.emptyList();;
      private void ensureClientIDsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          clientIDs_ = new java.util.ArrayList<java.lang.Integer>(clientIDs_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<java.lang.Integer>
          getClientIDsList() {
        return java.util.Collections.unmodifiableList(clientIDs_);
      }
      public int getClientIDsCount() {
        return clientIDs_.size();
      }
      public int getClientIDs(int index) {
        return clientIDs_.get(index);
      }
      public Builder setClientIDs(
          int index, int value) {
        ensureClientIDsIsMutable();
        clientIDs_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addClientIDs(int value) {
        ensureClientIDsIsMutable();
        clientIDs_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllClientIDs(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureClientIDsIsMutable();
        super.addAll(values, clientIDs_);
        onChanged();
        return this;
      }
      public Builder clearClientIDs() {
        clientIDs_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:amber.DriverHdr)
    }
    
    static {
      defaultInstance = new DriverHdr(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:amber.DriverHdr)
  }
  
  public interface DriverMsgOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<DriverMsg> {
    
    // required .amber.DriverMsg.MsgType type = 2;
    boolean hasType();
    amber.proto.AmberProto.DriverMsg.MsgType getType();
    
    // optional uint32 synNum = 3;
    boolean hasSynNum();
    int getSynNum();
    
    // optional uint32 ackNum = 4;
    boolean hasAckNum();
    int getAckNum();
    
    // optional uint32 listenerNum = 5;
    boolean hasListenerNum();
    int getListenerNum();
  }
  public static final class DriverMsg extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        DriverMsg> implements DriverMsgOrBuilder {
    // Use DriverMsg.newBuilder() to construct.
    private DriverMsg(Builder builder) {
      super(builder);
    }
    private DriverMsg(boolean noInit) {}
    
    private static final DriverMsg defaultInstance;
    public static DriverMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public DriverMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return amber.proto.AmberProto.internal_static_amber_DriverMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return amber.proto.AmberProto.internal_static_amber_DriverMsg_fieldAccessorTable;
    }
    
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      DATA(0, 1),
      PING(1, 2),
      PONG(2, 3),
      CLIENT_DIED(3, 4),
      DRIVER_DIED(4, 5),
      ;
      
      public static final int DATA_VALUE = 1;
      public static final int PING_VALUE = 2;
      public static final int PONG_VALUE = 3;
      public static final int CLIENT_DIED_VALUE = 4;
      public static final int DRIVER_DIED_VALUE = 5;
      
      
      public final int getNumber() { return value; }
      
      public static MsgType valueOf(int value) {
        switch (value) {
          case 1: return DATA;
          case 2: return PING;
          case 3: return PONG;
          case 4: return CLIENT_DIED;
          case 5: return DRIVER_DIED;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return amber.proto.AmberProto.DriverMsg.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final MsgType[] VALUES = {
        DATA, PING, PONG, CLIENT_DIED, DRIVER_DIED, 
      };
      
      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private MsgType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:amber.DriverMsg.MsgType)
    }
    
    private int bitField0_;
    // required .amber.DriverMsg.MsgType type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private amber.proto.AmberProto.DriverMsg.MsgType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public amber.proto.AmberProto.DriverMsg.MsgType getType() {
      return type_;
    }
    
    // optional uint32 synNum = 3;
    public static final int SYNNUM_FIELD_NUMBER = 3;
    private int synNum_;
    public boolean hasSynNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getSynNum() {
      return synNum_;
    }
    
    // optional uint32 ackNum = 4;
    public static final int ACKNUM_FIELD_NUMBER = 4;
    private int ackNum_;
    public boolean hasAckNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getAckNum() {
      return ackNum_;
    }
    
    // optional uint32 listenerNum = 5;
    public static final int LISTENERNUM_FIELD_NUMBER = 5;
    private int listenerNum_;
    public boolean hasListenerNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getListenerNum() {
      return listenerNum_;
    }
    
    private void initFields() {
      type_ = amber.proto.AmberProto.DriverMsg.MsgType.DATA;
      synNum_ = 0;
      ackNum_ = 0;
      listenerNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<amber.proto.AmberProto.DriverMsg>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(3, synNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(4, ackNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(5, listenerNum_);
      }
      extensionWriter.writeUntil(64, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, synNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, ackNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, listenerNum_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static amber.proto.AmberProto.DriverMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static amber.proto.AmberProto.DriverMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static amber.proto.AmberProto.DriverMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static amber.proto.AmberProto.DriverMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static amber.proto.AmberProto.DriverMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static amber.proto.AmberProto.DriverMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static amber.proto.AmberProto.DriverMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static amber.proto.AmberProto.DriverMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static amber.proto.AmberProto.DriverMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static amber.proto.AmberProto.DriverMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(amber.proto.AmberProto.DriverMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          amber.proto.AmberProto.DriverMsg, Builder> implements amber.proto.AmberProto.DriverMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return amber.proto.AmberProto.internal_static_amber_DriverMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return amber.proto.AmberProto.internal_static_amber_DriverMsg_fieldAccessorTable;
      }
      
      // Construct using amber.proto.AmberProto.DriverMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = amber.proto.AmberProto.DriverMsg.MsgType.DATA;
        bitField0_ = (bitField0_ & ~0x00000001);
        synNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        ackNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        listenerNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return amber.proto.AmberProto.DriverMsg.getDescriptor();
      }
      
      public amber.proto.AmberProto.DriverMsg getDefaultInstanceForType() {
        return amber.proto.AmberProto.DriverMsg.getDefaultInstance();
      }
      
      public amber.proto.AmberProto.DriverMsg build() {
        amber.proto.AmberProto.DriverMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private amber.proto.AmberProto.DriverMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        amber.proto.AmberProto.DriverMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public amber.proto.AmberProto.DriverMsg buildPartial() {
        amber.proto.AmberProto.DriverMsg result = new amber.proto.AmberProto.DriverMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.synNum_ = synNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ackNum_ = ackNum_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.listenerNum_ = listenerNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof amber.proto.AmberProto.DriverMsg) {
          return mergeFrom((amber.proto.AmberProto.DriverMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(amber.proto.AmberProto.DriverMsg other) {
        if (other == amber.proto.AmberProto.DriverMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSynNum()) {
          setSynNum(other.getSynNum());
        }
        if (other.hasAckNum()) {
          setAckNum(other.getAckNum());
        }
        if (other.hasListenerNum()) {
          setListenerNum(other.getListenerNum());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              amber.proto.AmberProto.DriverMsg.MsgType value = amber.proto.AmberProto.DriverMsg.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              synNum_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              ackNum_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              listenerNum_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .amber.DriverMsg.MsgType type = 2;
      private amber.proto.AmberProto.DriverMsg.MsgType type_ = amber.proto.AmberProto.DriverMsg.MsgType.DATA;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public amber.proto.AmberProto.DriverMsg.MsgType getType() {
        return type_;
      }
      public Builder setType(amber.proto.AmberProto.DriverMsg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = amber.proto.AmberProto.DriverMsg.MsgType.DATA;
        onChanged();
        return this;
      }
      
      // optional uint32 synNum = 3;
      private int synNum_ ;
      public boolean hasSynNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getSynNum() {
        return synNum_;
      }
      public Builder setSynNum(int value) {
        bitField0_ |= 0x00000002;
        synNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearSynNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        synNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 ackNum = 4;
      private int ackNum_ ;
      public boolean hasAckNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getAckNum() {
        return ackNum_;
      }
      public Builder setAckNum(int value) {
        bitField0_ |= 0x00000004;
        ackNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearAckNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ackNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 listenerNum = 5;
      private int listenerNum_ ;
      public boolean hasListenerNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getListenerNum() {
        return listenerNum_;
      }
      public Builder setListenerNum(int value) {
        bitField0_ |= 0x00000008;
        listenerNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearListenerNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        listenerNum_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:amber.DriverMsg)
    }
    
    static {
      defaultInstance = new DriverMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:amber.DriverMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_DriverHdr_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_DriverHdr_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_DriverMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_DriverMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017drivermsg.proto\022\005amber\"H\n\tDriverHdr\022\022\n" +
      "\ndeviceType\030\001 \001(\005\022\020\n\010deviceID\030\002 \001(\005\022\025\n\tc" +
      "lientIDs\030\003 \003(\005B\002\020\001\"\271\001\n\tDriverMsg\022&\n\004type" +
      "\030\002 \002(\0162\030.amber.DriverMsg.MsgType\022\016\n\006synN" +
      "um\030\003 \001(\r\022\016\n\006ackNum\030\004 \001(\r\022\023\n\013listenerNum\030" +
      "\005 \001(\r\"I\n\007MsgType\022\010\n\004DATA\020\001\022\010\n\004PING\020\002\022\010\n\004" +
      "PONG\020\003\022\017\n\013CLIENT_DIED\020\004\022\017\n\013DRIVER_DIED\020\005" +
      "*\004\010\010\020@*6\n\nDeviceType\022\013\n\007NINEDOF\020\001\022\014\n\010ROB" +
      "OCLAW\020\002\022\r\n\tSTARGAZER\020\003B\033\n\013amber.protoB\nA" +
      "mberProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_amber_DriverHdr_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_amber_DriverHdr_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_DriverHdr_descriptor,
              new java.lang.String[] { "DeviceType", "DeviceID", "ClientIDs", },
              amber.proto.AmberProto.DriverHdr.class,
              amber.proto.AmberProto.DriverHdr.Builder.class);
          internal_static_amber_DriverMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_amber_DriverMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_DriverMsg_descriptor,
              new java.lang.String[] { "Type", "SynNum", "AckNum", "ListenerNum", },
              amber.proto.AmberProto.DriverMsg.class,
              amber.proto.AmberProto.DriverMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
