#!/bin/sh

set -x 

export RUNCMD=".run_cmd.tmp"
export PWD="$(pwd)"

export HEART_COMMAND="$(which sh) $PWD/$RUNCMD"

cat > "$RUNCMD" <<EOF
run_erl -daemon pipes/ log/ 'erl -boot start_sasl -pa $PWD/apps/*/ebin -pa $PWD/deps/*/ebin -mnesia $PWD/priv/mnesia -s mnesia -s amber -heart'
EOF

sh "$RUNCMD"