#!/bin/sh

erl -pa apps/*/ebin -pa deps/*/ebin -pz apps/*/.eunit -mnesia priv/mnesia -boot start_sasl -s mnesia -s amber

# TODO: usunąć jak już driver będzie potrafił sam się zamknąć
killall roboclaw_driver
killall stargazer_driver
