// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ninedof.proto

package ninedof.proto;

public final class NinedofProto {
  private NinedofProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(ninedof.proto.NinedofProto.sensorData);
    registry.add(ninedof.proto.NinedofProto.dataRequest);
    registry.add(ninedof.proto.NinedofProto.subscribeAction);
  }
  public interface SensorDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .amber.ninedof_proto.SensorData.AxisData accel = 1;
    boolean hasAccel();
    ninedof.proto.NinedofProto.SensorData.AxisData getAccel();
    ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder getAccelOrBuilder();
    
    // optional .amber.ninedof_proto.SensorData.AxisData gyro = 2;
    boolean hasGyro();
    ninedof.proto.NinedofProto.SensorData.AxisData getGyro();
    ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder getGyroOrBuilder();
    
    // optional .amber.ninedof_proto.SensorData.AxisData magnet = 3;
    boolean hasMagnet();
    ninedof.proto.NinedofProto.SensorData.AxisData getMagnet();
    ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder getMagnetOrBuilder();
  }
  public static final class SensorData extends
      com.google.protobuf.GeneratedMessage
      implements SensorDataOrBuilder {
    // Use SensorData.newBuilder() to construct.
    private SensorData(Builder builder) {
      super(builder);
    }
    private SensorData(boolean noInit) {}
    
    private static final SensorData defaultInstance;
    public static SensorData getDefaultInstance() {
      return defaultInstance;
    }
    
    public SensorData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_SensorData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_SensorData_fieldAccessorTable;
    }
    
    public interface AxisDataOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required sint32 xAxis = 1;
      boolean hasXAxis();
      int getXAxis();
      
      // required sint32 yAxis = 2;
      boolean hasYAxis();
      int getYAxis();
      
      // required sint32 zAxis = 3;
      boolean hasZAxis();
      int getZAxis();
    }
    public static final class AxisData extends
        com.google.protobuf.GeneratedMessage
        implements AxisDataOrBuilder {
      // Use AxisData.newBuilder() to construct.
      private AxisData(Builder builder) {
        super(builder);
      }
      private AxisData(boolean noInit) {}
      
      private static final AxisData defaultInstance;
      public static AxisData getDefaultInstance() {
        return defaultInstance;
      }
      
      public AxisData getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_SensorData_AxisData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_SensorData_AxisData_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required sint32 xAxis = 1;
      public static final int XAXIS_FIELD_NUMBER = 1;
      private int xAxis_;
      public boolean hasXAxis() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getXAxis() {
        return xAxis_;
      }
      
      // required sint32 yAxis = 2;
      public static final int YAXIS_FIELD_NUMBER = 2;
      private int yAxis_;
      public boolean hasYAxis() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getYAxis() {
        return yAxis_;
      }
      
      // required sint32 zAxis = 3;
      public static final int ZAXIS_FIELD_NUMBER = 3;
      private int zAxis_;
      public boolean hasZAxis() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getZAxis() {
        return zAxis_;
      }
      
      private void initFields() {
        xAxis_ = 0;
        yAxis_ = 0;
        zAxis_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasXAxis()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasYAxis()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasZAxis()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeSInt32(1, xAxis_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeSInt32(2, yAxis_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeSInt32(3, zAxis_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt32Size(1, xAxis_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt32Size(2, yAxis_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt32Size(3, zAxis_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static ninedof.proto.NinedofProto.SensorData.AxisData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static ninedof.proto.NinedofProto.SensorData.AxisData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static ninedof.proto.NinedofProto.SensorData.AxisData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static ninedof.proto.NinedofProto.SensorData.AxisData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static ninedof.proto.NinedofProto.SensorData.AxisData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static ninedof.proto.NinedofProto.SensorData.AxisData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static ninedof.proto.NinedofProto.SensorData.AxisData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static ninedof.proto.NinedofProto.SensorData.AxisData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static ninedof.proto.NinedofProto.SensorData.AxisData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static ninedof.proto.NinedofProto.SensorData.AxisData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ninedof.proto.NinedofProto.SensorData.AxisData prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_SensorData_AxisData_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_SensorData_AxisData_fieldAccessorTable;
        }
        
        // Construct using ninedof.proto.NinedofProto.SensorData.AxisData.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          xAxis_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          yAxis_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          zAxis_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ninedof.proto.NinedofProto.SensorData.AxisData.getDescriptor();
        }
        
        public ninedof.proto.NinedofProto.SensorData.AxisData getDefaultInstanceForType() {
          return ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
        }
        
        public ninedof.proto.NinedofProto.SensorData.AxisData build() {
          ninedof.proto.NinedofProto.SensorData.AxisData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private ninedof.proto.NinedofProto.SensorData.AxisData buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          ninedof.proto.NinedofProto.SensorData.AxisData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public ninedof.proto.NinedofProto.SensorData.AxisData buildPartial() {
          ninedof.proto.NinedofProto.SensorData.AxisData result = new ninedof.proto.NinedofProto.SensorData.AxisData(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.xAxis_ = xAxis_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.yAxis_ = yAxis_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.zAxis_ = zAxis_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ninedof.proto.NinedofProto.SensorData.AxisData) {
            return mergeFrom((ninedof.proto.NinedofProto.SensorData.AxisData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(ninedof.proto.NinedofProto.SensorData.AxisData other) {
          if (other == ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance()) return this;
          if (other.hasXAxis()) {
            setXAxis(other.getXAxis());
          }
          if (other.hasYAxis()) {
            setYAxis(other.getYAxis());
          }
          if (other.hasZAxis()) {
            setZAxis(other.getZAxis());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasXAxis()) {
            
            return false;
          }
          if (!hasYAxis()) {
            
            return false;
          }
          if (!hasZAxis()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                xAxis_ = input.readSInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                yAxis_ = input.readSInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                zAxis_ = input.readSInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required sint32 xAxis = 1;
        private int xAxis_ ;
        public boolean hasXAxis() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getXAxis() {
          return xAxis_;
        }
        public Builder setXAxis(int value) {
          bitField0_ |= 0x00000001;
          xAxis_ = value;
          onChanged();
          return this;
        }
        public Builder clearXAxis() {
          bitField0_ = (bitField0_ & ~0x00000001);
          xAxis_ = 0;
          onChanged();
          return this;
        }
        
        // required sint32 yAxis = 2;
        private int yAxis_ ;
        public boolean hasYAxis() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getYAxis() {
          return yAxis_;
        }
        public Builder setYAxis(int value) {
          bitField0_ |= 0x00000002;
          yAxis_ = value;
          onChanged();
          return this;
        }
        public Builder clearYAxis() {
          bitField0_ = (bitField0_ & ~0x00000002);
          yAxis_ = 0;
          onChanged();
          return this;
        }
        
        // required sint32 zAxis = 3;
        private int zAxis_ ;
        public boolean hasZAxis() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public int getZAxis() {
          return zAxis_;
        }
        public Builder setZAxis(int value) {
          bitField0_ |= 0x00000004;
          zAxis_ = value;
          onChanged();
          return this;
        }
        public Builder clearZAxis() {
          bitField0_ = (bitField0_ & ~0x00000004);
          zAxis_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:amber.ninedof_proto.SensorData.AxisData)
      }
      
      static {
        defaultInstance = new AxisData(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:amber.ninedof_proto.SensorData.AxisData)
    }
    
    private int bitField0_;
    // optional .amber.ninedof_proto.SensorData.AxisData accel = 1;
    public static final int ACCEL_FIELD_NUMBER = 1;
    private ninedof.proto.NinedofProto.SensorData.AxisData accel_;
    public boolean hasAccel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public ninedof.proto.NinedofProto.SensorData.AxisData getAccel() {
      return accel_;
    }
    public ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder getAccelOrBuilder() {
      return accel_;
    }
    
    // optional .amber.ninedof_proto.SensorData.AxisData gyro = 2;
    public static final int GYRO_FIELD_NUMBER = 2;
    private ninedof.proto.NinedofProto.SensorData.AxisData gyro_;
    public boolean hasGyro() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public ninedof.proto.NinedofProto.SensorData.AxisData getGyro() {
      return gyro_;
    }
    public ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder getGyroOrBuilder() {
      return gyro_;
    }
    
    // optional .amber.ninedof_proto.SensorData.AxisData magnet = 3;
    public static final int MAGNET_FIELD_NUMBER = 3;
    private ninedof.proto.NinedofProto.SensorData.AxisData magnet_;
    public boolean hasMagnet() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public ninedof.proto.NinedofProto.SensorData.AxisData getMagnet() {
      return magnet_;
    }
    public ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder getMagnetOrBuilder() {
      return magnet_;
    }
    
    private void initFields() {
      accel_ = ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
      gyro_ = ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
      magnet_ = ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasAccel()) {
        if (!getAccel().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGyro()) {
        if (!getGyro().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasMagnet()) {
        if (!getMagnet().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, accel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, gyro_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, magnet_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, accel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, gyro_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, magnet_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ninedof.proto.NinedofProto.SensorData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ninedof.proto.NinedofProto.SensorData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ninedof.proto.NinedofProto.SensorData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ninedof.proto.NinedofProto.SensorData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ninedof.proto.NinedofProto.SensorData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ninedof.proto.NinedofProto.SensorData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ninedof.proto.NinedofProto.SensorData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ninedof.proto.NinedofProto.SensorData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ninedof.proto.NinedofProto.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ninedof.proto.NinedofProto.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ninedof.proto.NinedofProto.SensorData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ninedof.proto.NinedofProto.SensorDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_SensorData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_SensorData_fieldAccessorTable;
      }
      
      // Construct using ninedof.proto.NinedofProto.SensorData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAccelFieldBuilder();
          getGyroFieldBuilder();
          getMagnetFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (accelBuilder_ == null) {
          accel_ = ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
        } else {
          accelBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (gyroBuilder_ == null) {
          gyro_ = ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
        } else {
          gyroBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (magnetBuilder_ == null) {
          magnet_ = ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
        } else {
          magnetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ninedof.proto.NinedofProto.SensorData.getDescriptor();
      }
      
      public ninedof.proto.NinedofProto.SensorData getDefaultInstanceForType() {
        return ninedof.proto.NinedofProto.SensorData.getDefaultInstance();
      }
      
      public ninedof.proto.NinedofProto.SensorData build() {
        ninedof.proto.NinedofProto.SensorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ninedof.proto.NinedofProto.SensorData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ninedof.proto.NinedofProto.SensorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ninedof.proto.NinedofProto.SensorData buildPartial() {
        ninedof.proto.NinedofProto.SensorData result = new ninedof.proto.NinedofProto.SensorData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (accelBuilder_ == null) {
          result.accel_ = accel_;
        } else {
          result.accel_ = accelBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (gyroBuilder_ == null) {
          result.gyro_ = gyro_;
        } else {
          result.gyro_ = gyroBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (magnetBuilder_ == null) {
          result.magnet_ = magnet_;
        } else {
          result.magnet_ = magnetBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ninedof.proto.NinedofProto.SensorData) {
          return mergeFrom((ninedof.proto.NinedofProto.SensorData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ninedof.proto.NinedofProto.SensorData other) {
        if (other == ninedof.proto.NinedofProto.SensorData.getDefaultInstance()) return this;
        if (other.hasAccel()) {
          mergeAccel(other.getAccel());
        }
        if (other.hasGyro()) {
          mergeGyro(other.getGyro());
        }
        if (other.hasMagnet()) {
          mergeMagnet(other.getMagnet());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasAccel()) {
          if (!getAccel().isInitialized()) {
            
            return false;
          }
        }
        if (hasGyro()) {
          if (!getGyro().isInitialized()) {
            
            return false;
          }
        }
        if (hasMagnet()) {
          if (!getMagnet().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ninedof.proto.NinedofProto.SensorData.AxisData.Builder subBuilder = ninedof.proto.NinedofProto.SensorData.AxisData.newBuilder();
              if (hasAccel()) {
                subBuilder.mergeFrom(getAccel());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setAccel(subBuilder.buildPartial());
              break;
            }
            case 18: {
              ninedof.proto.NinedofProto.SensorData.AxisData.Builder subBuilder = ninedof.proto.NinedofProto.SensorData.AxisData.newBuilder();
              if (hasGyro()) {
                subBuilder.mergeFrom(getGyro());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGyro(subBuilder.buildPartial());
              break;
            }
            case 26: {
              ninedof.proto.NinedofProto.SensorData.AxisData.Builder subBuilder = ninedof.proto.NinedofProto.SensorData.AxisData.newBuilder();
              if (hasMagnet()) {
                subBuilder.mergeFrom(getMagnet());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMagnet(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .amber.ninedof_proto.SensorData.AxisData accel = 1;
      private ninedof.proto.NinedofProto.SensorData.AxisData accel_ = ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ninedof.proto.NinedofProto.SensorData.AxisData, ninedof.proto.NinedofProto.SensorData.AxisData.Builder, ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder> accelBuilder_;
      public boolean hasAccel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public ninedof.proto.NinedofProto.SensorData.AxisData getAccel() {
        if (accelBuilder_ == null) {
          return accel_;
        } else {
          return accelBuilder_.getMessage();
        }
      }
      public Builder setAccel(ninedof.proto.NinedofProto.SensorData.AxisData value) {
        if (accelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          accel_ = value;
          onChanged();
        } else {
          accelBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setAccel(
          ninedof.proto.NinedofProto.SensorData.AxisData.Builder builderForValue) {
        if (accelBuilder_ == null) {
          accel_ = builderForValue.build();
          onChanged();
        } else {
          accelBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeAccel(ninedof.proto.NinedofProto.SensorData.AxisData value) {
        if (accelBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              accel_ != ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance()) {
            accel_ =
              ninedof.proto.NinedofProto.SensorData.AxisData.newBuilder(accel_).mergeFrom(value).buildPartial();
          } else {
            accel_ = value;
          }
          onChanged();
        } else {
          accelBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearAccel() {
        if (accelBuilder_ == null) {
          accel_ = ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
          onChanged();
        } else {
          accelBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public ninedof.proto.NinedofProto.SensorData.AxisData.Builder getAccelBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAccelFieldBuilder().getBuilder();
      }
      public ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder getAccelOrBuilder() {
        if (accelBuilder_ != null) {
          return accelBuilder_.getMessageOrBuilder();
        } else {
          return accel_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          ninedof.proto.NinedofProto.SensorData.AxisData, ninedof.proto.NinedofProto.SensorData.AxisData.Builder, ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder> 
          getAccelFieldBuilder() {
        if (accelBuilder_ == null) {
          accelBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ninedof.proto.NinedofProto.SensorData.AxisData, ninedof.proto.NinedofProto.SensorData.AxisData.Builder, ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder>(
                  accel_,
                  getParentForChildren(),
                  isClean());
          accel_ = null;
        }
        return accelBuilder_;
      }
      
      // optional .amber.ninedof_proto.SensorData.AxisData gyro = 2;
      private ninedof.proto.NinedofProto.SensorData.AxisData gyro_ = ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ninedof.proto.NinedofProto.SensorData.AxisData, ninedof.proto.NinedofProto.SensorData.AxisData.Builder, ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder> gyroBuilder_;
      public boolean hasGyro() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public ninedof.proto.NinedofProto.SensorData.AxisData getGyro() {
        if (gyroBuilder_ == null) {
          return gyro_;
        } else {
          return gyroBuilder_.getMessage();
        }
      }
      public Builder setGyro(ninedof.proto.NinedofProto.SensorData.AxisData value) {
        if (gyroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gyro_ = value;
          onChanged();
        } else {
          gyroBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setGyro(
          ninedof.proto.NinedofProto.SensorData.AxisData.Builder builderForValue) {
        if (gyroBuilder_ == null) {
          gyro_ = builderForValue.build();
          onChanged();
        } else {
          gyroBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeGyro(ninedof.proto.NinedofProto.SensorData.AxisData value) {
        if (gyroBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              gyro_ != ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance()) {
            gyro_ =
              ninedof.proto.NinedofProto.SensorData.AxisData.newBuilder(gyro_).mergeFrom(value).buildPartial();
          } else {
            gyro_ = value;
          }
          onChanged();
        } else {
          gyroBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearGyro() {
        if (gyroBuilder_ == null) {
          gyro_ = ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
          onChanged();
        } else {
          gyroBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public ninedof.proto.NinedofProto.SensorData.AxisData.Builder getGyroBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getGyroFieldBuilder().getBuilder();
      }
      public ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder getGyroOrBuilder() {
        if (gyroBuilder_ != null) {
          return gyroBuilder_.getMessageOrBuilder();
        } else {
          return gyro_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          ninedof.proto.NinedofProto.SensorData.AxisData, ninedof.proto.NinedofProto.SensorData.AxisData.Builder, ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder> 
          getGyroFieldBuilder() {
        if (gyroBuilder_ == null) {
          gyroBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ninedof.proto.NinedofProto.SensorData.AxisData, ninedof.proto.NinedofProto.SensorData.AxisData.Builder, ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder>(
                  gyro_,
                  getParentForChildren(),
                  isClean());
          gyro_ = null;
        }
        return gyroBuilder_;
      }
      
      // optional .amber.ninedof_proto.SensorData.AxisData magnet = 3;
      private ninedof.proto.NinedofProto.SensorData.AxisData magnet_ = ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ninedof.proto.NinedofProto.SensorData.AxisData, ninedof.proto.NinedofProto.SensorData.AxisData.Builder, ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder> magnetBuilder_;
      public boolean hasMagnet() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public ninedof.proto.NinedofProto.SensorData.AxisData getMagnet() {
        if (magnetBuilder_ == null) {
          return magnet_;
        } else {
          return magnetBuilder_.getMessage();
        }
      }
      public Builder setMagnet(ninedof.proto.NinedofProto.SensorData.AxisData value) {
        if (magnetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          magnet_ = value;
          onChanged();
        } else {
          magnetBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setMagnet(
          ninedof.proto.NinedofProto.SensorData.AxisData.Builder builderForValue) {
        if (magnetBuilder_ == null) {
          magnet_ = builderForValue.build();
          onChanged();
        } else {
          magnetBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeMagnet(ninedof.proto.NinedofProto.SensorData.AxisData value) {
        if (magnetBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              magnet_ != ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance()) {
            magnet_ =
              ninedof.proto.NinedofProto.SensorData.AxisData.newBuilder(magnet_).mergeFrom(value).buildPartial();
          } else {
            magnet_ = value;
          }
          onChanged();
        } else {
          magnetBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearMagnet() {
        if (magnetBuilder_ == null) {
          magnet_ = ninedof.proto.NinedofProto.SensorData.AxisData.getDefaultInstance();
          onChanged();
        } else {
          magnetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public ninedof.proto.NinedofProto.SensorData.AxisData.Builder getMagnetBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMagnetFieldBuilder().getBuilder();
      }
      public ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder getMagnetOrBuilder() {
        if (magnetBuilder_ != null) {
          return magnetBuilder_.getMessageOrBuilder();
        } else {
          return magnet_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          ninedof.proto.NinedofProto.SensorData.AxisData, ninedof.proto.NinedofProto.SensorData.AxisData.Builder, ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder> 
          getMagnetFieldBuilder() {
        if (magnetBuilder_ == null) {
          magnetBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ninedof.proto.NinedofProto.SensorData.AxisData, ninedof.proto.NinedofProto.SensorData.AxisData.Builder, ninedof.proto.NinedofProto.SensorData.AxisDataOrBuilder>(
                  magnet_,
                  getParentForChildren(),
                  isClean());
          magnet_ = null;
        }
        return magnetBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:amber.ninedof_proto.SensorData)
    }
    
    static {
      defaultInstance = new SensorData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:amber.ninedof_proto.SensorData)
  }
  
  public interface DataRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bool accel = 1;
    boolean hasAccel();
    boolean getAccel();
    
    // optional bool gyro = 2;
    boolean hasGyro();
    boolean getGyro();
    
    // optional bool magnet = 3;
    boolean hasMagnet();
    boolean getMagnet();
  }
  public static final class DataRequest extends
      com.google.protobuf.GeneratedMessage
      implements DataRequestOrBuilder {
    // Use DataRequest.newBuilder() to construct.
    private DataRequest(Builder builder) {
      super(builder);
    }
    private DataRequest(boolean noInit) {}
    
    private static final DataRequest defaultInstance;
    public static DataRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public DataRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_DataRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_DataRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bool accel = 1;
    public static final int ACCEL_FIELD_NUMBER = 1;
    private boolean accel_;
    public boolean hasAccel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getAccel() {
      return accel_;
    }
    
    // optional bool gyro = 2;
    public static final int GYRO_FIELD_NUMBER = 2;
    private boolean gyro_;
    public boolean hasGyro() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getGyro() {
      return gyro_;
    }
    
    // optional bool magnet = 3;
    public static final int MAGNET_FIELD_NUMBER = 3;
    private boolean magnet_;
    public boolean hasMagnet() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getMagnet() {
      return magnet_;
    }
    
    private void initFields() {
      accel_ = false;
      gyro_ = false;
      magnet_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, accel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, gyro_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, magnet_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, accel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, gyro_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, magnet_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ninedof.proto.NinedofProto.DataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ninedof.proto.NinedofProto.DataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ninedof.proto.NinedofProto.DataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ninedof.proto.NinedofProto.DataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ninedof.proto.NinedofProto.DataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ninedof.proto.NinedofProto.DataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ninedof.proto.NinedofProto.DataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ninedof.proto.NinedofProto.DataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ninedof.proto.NinedofProto.DataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ninedof.proto.NinedofProto.DataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ninedof.proto.NinedofProto.DataRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ninedof.proto.NinedofProto.DataRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_DataRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_DataRequest_fieldAccessorTable;
      }
      
      // Construct using ninedof.proto.NinedofProto.DataRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        accel_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        gyro_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        magnet_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ninedof.proto.NinedofProto.DataRequest.getDescriptor();
      }
      
      public ninedof.proto.NinedofProto.DataRequest getDefaultInstanceForType() {
        return ninedof.proto.NinedofProto.DataRequest.getDefaultInstance();
      }
      
      public ninedof.proto.NinedofProto.DataRequest build() {
        ninedof.proto.NinedofProto.DataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ninedof.proto.NinedofProto.DataRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ninedof.proto.NinedofProto.DataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ninedof.proto.NinedofProto.DataRequest buildPartial() {
        ninedof.proto.NinedofProto.DataRequest result = new ninedof.proto.NinedofProto.DataRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accel_ = accel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gyro_ = gyro_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.magnet_ = magnet_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ninedof.proto.NinedofProto.DataRequest) {
          return mergeFrom((ninedof.proto.NinedofProto.DataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ninedof.proto.NinedofProto.DataRequest other) {
        if (other == ninedof.proto.NinedofProto.DataRequest.getDefaultInstance()) return this;
        if (other.hasAccel()) {
          setAccel(other.getAccel());
        }
        if (other.hasGyro()) {
          setGyro(other.getGyro());
        }
        if (other.hasMagnet()) {
          setMagnet(other.getMagnet());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              accel_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              gyro_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              magnet_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bool accel = 1;
      private boolean accel_ ;
      public boolean hasAccel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getAccel() {
        return accel_;
      }
      public Builder setAccel(boolean value) {
        bitField0_ |= 0x00000001;
        accel_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accel_ = false;
        onChanged();
        return this;
      }
      
      // optional bool gyro = 2;
      private boolean gyro_ ;
      public boolean hasGyro() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getGyro() {
        return gyro_;
      }
      public Builder setGyro(boolean value) {
        bitField0_ |= 0x00000002;
        gyro_ = value;
        onChanged();
        return this;
      }
      public Builder clearGyro() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gyro_ = false;
        onChanged();
        return this;
      }
      
      // optional bool magnet = 3;
      private boolean magnet_ ;
      public boolean hasMagnet() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getMagnet() {
        return magnet_;
      }
      public Builder setMagnet(boolean value) {
        bitField0_ |= 0x00000004;
        magnet_ = value;
        onChanged();
        return this;
      }
      public Builder clearMagnet() {
        bitField0_ = (bitField0_ & ~0x00000004);
        magnet_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:amber.ninedof_proto.DataRequest)
    }
    
    static {
      defaultInstance = new DataRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:amber.ninedof_proto.DataRequest)
  }
  
  public interface SubscribeActionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 freq = 1;
    boolean hasFreq();
    int getFreq();
    
    // optional bool accel = 2;
    boolean hasAccel();
    boolean getAccel();
    
    // optional bool gyro = 3;
    boolean hasGyro();
    boolean getGyro();
    
    // optional bool magnet = 4;
    boolean hasMagnet();
    boolean getMagnet();
  }
  public static final class SubscribeAction extends
      com.google.protobuf.GeneratedMessage
      implements SubscribeActionOrBuilder {
    // Use SubscribeAction.newBuilder() to construct.
    private SubscribeAction(Builder builder) {
      super(builder);
    }
    private SubscribeAction(boolean noInit) {}
    
    private static final SubscribeAction defaultInstance;
    public static SubscribeAction getDefaultInstance() {
      return defaultInstance;
    }
    
    public SubscribeAction getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_SubscribeAction_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_SubscribeAction_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 freq = 1;
    public static final int FREQ_FIELD_NUMBER = 1;
    private int freq_;
    public boolean hasFreq() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getFreq() {
      return freq_;
    }
    
    // optional bool accel = 2;
    public static final int ACCEL_FIELD_NUMBER = 2;
    private boolean accel_;
    public boolean hasAccel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getAccel() {
      return accel_;
    }
    
    // optional bool gyro = 3;
    public static final int GYRO_FIELD_NUMBER = 3;
    private boolean gyro_;
    public boolean hasGyro() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getGyro() {
      return gyro_;
    }
    
    // optional bool magnet = 4;
    public static final int MAGNET_FIELD_NUMBER = 4;
    private boolean magnet_;
    public boolean hasMagnet() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getMagnet() {
      return magnet_;
    }
    
    private void initFields() {
      freq_ = 0;
      accel_ = false;
      gyro_ = false;
      magnet_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, freq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, accel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, gyro_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, magnet_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, freq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, accel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, gyro_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, magnet_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ninedof.proto.NinedofProto.SubscribeAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ninedof.proto.NinedofProto.SubscribeAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ninedof.proto.NinedofProto.SubscribeAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ninedof.proto.NinedofProto.SubscribeAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ninedof.proto.NinedofProto.SubscribeAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ninedof.proto.NinedofProto.SubscribeAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ninedof.proto.NinedofProto.SubscribeAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ninedof.proto.NinedofProto.SubscribeAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ninedof.proto.NinedofProto.SubscribeAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ninedof.proto.NinedofProto.SubscribeAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ninedof.proto.NinedofProto.SubscribeAction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ninedof.proto.NinedofProto.SubscribeActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_SubscribeAction_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ninedof.proto.NinedofProto.internal_static_amber_ninedof_proto_SubscribeAction_fieldAccessorTable;
      }
      
      // Construct using ninedof.proto.NinedofProto.SubscribeAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        freq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        accel_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        gyro_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        magnet_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ninedof.proto.NinedofProto.SubscribeAction.getDescriptor();
      }
      
      public ninedof.proto.NinedofProto.SubscribeAction getDefaultInstanceForType() {
        return ninedof.proto.NinedofProto.SubscribeAction.getDefaultInstance();
      }
      
      public ninedof.proto.NinedofProto.SubscribeAction build() {
        ninedof.proto.NinedofProto.SubscribeAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ninedof.proto.NinedofProto.SubscribeAction buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ninedof.proto.NinedofProto.SubscribeAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ninedof.proto.NinedofProto.SubscribeAction buildPartial() {
        ninedof.proto.NinedofProto.SubscribeAction result = new ninedof.proto.NinedofProto.SubscribeAction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.freq_ = freq_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accel_ = accel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gyro_ = gyro_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.magnet_ = magnet_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ninedof.proto.NinedofProto.SubscribeAction) {
          return mergeFrom((ninedof.proto.NinedofProto.SubscribeAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ninedof.proto.NinedofProto.SubscribeAction other) {
        if (other == ninedof.proto.NinedofProto.SubscribeAction.getDefaultInstance()) return this;
        if (other.hasFreq()) {
          setFreq(other.getFreq());
        }
        if (other.hasAccel()) {
          setAccel(other.getAccel());
        }
        if (other.hasGyro()) {
          setGyro(other.getGyro());
        }
        if (other.hasMagnet()) {
          setMagnet(other.getMagnet());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              freq_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              accel_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              gyro_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              magnet_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 freq = 1;
      private int freq_ ;
      public boolean hasFreq() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getFreq() {
        return freq_;
      }
      public Builder setFreq(int value) {
        bitField0_ |= 0x00000001;
        freq_ = value;
        onChanged();
        return this;
      }
      public Builder clearFreq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        freq_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool accel = 2;
      private boolean accel_ ;
      public boolean hasAccel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getAccel() {
        return accel_;
      }
      public Builder setAccel(boolean value) {
        bitField0_ |= 0x00000002;
        accel_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accel_ = false;
        onChanged();
        return this;
      }
      
      // optional bool gyro = 3;
      private boolean gyro_ ;
      public boolean hasGyro() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getGyro() {
        return gyro_;
      }
      public Builder setGyro(boolean value) {
        bitField0_ |= 0x00000004;
        gyro_ = value;
        onChanged();
        return this;
      }
      public Builder clearGyro() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gyro_ = false;
        onChanged();
        return this;
      }
      
      // optional bool magnet = 4;
      private boolean magnet_ ;
      public boolean hasMagnet() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getMagnet() {
        return magnet_;
      }
      public Builder setMagnet(boolean value) {
        bitField0_ |= 0x00000008;
        magnet_ = value;
        onChanged();
        return this;
      }
      public Builder clearMagnet() {
        bitField0_ = (bitField0_ & ~0x00000008);
        magnet_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:amber.ninedof_proto.SubscribeAction)
    }
    
    static {
      defaultInstance = new SubscribeAction(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:amber.ninedof_proto.SubscribeAction)
  }
  
  public static final int SENSORDATA_FIELD_NUMBER = 10;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      amber.proto.AmberProto.DriverMsg,
      ninedof.proto.NinedofProto.SensorData> sensorData = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        ninedof.proto.NinedofProto.SensorData.class,
        ninedof.proto.NinedofProto.SensorData.getDefaultInstance());
  public static final int DATAREQUEST_FIELD_NUMBER = 11;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      amber.proto.AmberProto.DriverMsg,
      ninedof.proto.NinedofProto.DataRequest> dataRequest = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        ninedof.proto.NinedofProto.DataRequest.class,
        ninedof.proto.NinedofProto.DataRequest.getDefaultInstance());
  public static final int SUBSCRIBEACTION_FIELD_NUMBER = 12;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      amber.proto.AmberProto.DriverMsg,
      ninedof.proto.NinedofProto.SubscribeAction> subscribeAction = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        ninedof.proto.NinedofProto.SubscribeAction.class,
        ninedof.proto.NinedofProto.SubscribeAction.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_ninedof_proto_SensorData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_ninedof_proto_SensorData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_ninedof_proto_SensorData_AxisData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_ninedof_proto_SensorData_AxisData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_ninedof_proto_DataRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_ninedof_proto_DataRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_ninedof_proto_SubscribeAction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_ninedof_proto_SubscribeAction_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rninedof.proto\022\023amber.ninedof_proto\032\017dr" +
      "ivermsg.proto\"\360\001\n\nSensorData\0227\n\005accel\030\001 " +
      "\001(\0132(.amber.ninedof_proto.SensorData.Axi" +
      "sData\0226\n\004gyro\030\002 \001(\0132(.amber.ninedof_prot" +
      "o.SensorData.AxisData\0228\n\006magnet\030\003 \001(\0132(." +
      "amber.ninedof_proto.SensorData.AxisData\032" +
      "7\n\010AxisData\022\r\n\005xAxis\030\001 \002(\021\022\r\n\005yAxis\030\002 \002(" +
      "\021\022\r\n\005zAxis\030\003 \002(\021\":\n\013DataRequest\022\r\n\005accel" +
      "\030\001 \001(\010\022\014\n\004gyro\030\002 \001(\010\022\016\n\006magnet\030\003 \001(\010\"L\n\017" +
      "SubscribeAction\022\014\n\004freq\030\001 \001(\r\022\r\n\005accel\030\002",
      " \001(\010\022\014\n\004gyro\030\003 \001(\010\022\016\n\006magnet\030\004 \001(\010:E\n\nse" +
      "nsorData\022\020.amber.DriverMsg\030\n \001(\0132\037.amber" +
      ".ninedof_proto.SensorData:G\n\013dataRequest" +
      "\022\020.amber.DriverMsg\030\013 \001(\0132 .amber.ninedof" +
      "_proto.DataRequest:O\n\017subscribeAction\022\020." +
      "amber.DriverMsg\030\014 \001(\0132$.amber.ninedof_pr" +
      "oto.SubscribeActionB\035\n\rninedof.protoB\014Ni" +
      "nedofProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_amber_ninedof_proto_SensorData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_amber_ninedof_proto_SensorData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_ninedof_proto_SensorData_descriptor,
              new java.lang.String[] { "Accel", "Gyro", "Magnet", },
              ninedof.proto.NinedofProto.SensorData.class,
              ninedof.proto.NinedofProto.SensorData.Builder.class);
          internal_static_amber_ninedof_proto_SensorData_AxisData_descriptor =
            internal_static_amber_ninedof_proto_SensorData_descriptor.getNestedTypes().get(0);
          internal_static_amber_ninedof_proto_SensorData_AxisData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_ninedof_proto_SensorData_AxisData_descriptor,
              new java.lang.String[] { "XAxis", "YAxis", "ZAxis", },
              ninedof.proto.NinedofProto.SensorData.AxisData.class,
              ninedof.proto.NinedofProto.SensorData.AxisData.Builder.class);
          internal_static_amber_ninedof_proto_DataRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_amber_ninedof_proto_DataRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_ninedof_proto_DataRequest_descriptor,
              new java.lang.String[] { "Accel", "Gyro", "Magnet", },
              ninedof.proto.NinedofProto.DataRequest.class,
              ninedof.proto.NinedofProto.DataRequest.Builder.class);
          internal_static_amber_ninedof_proto_SubscribeAction_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_amber_ninedof_proto_SubscribeAction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_ninedof_proto_SubscribeAction_descriptor,
              new java.lang.String[] { "Freq", "Accel", "Gyro", "Magnet", },
              ninedof.proto.NinedofProto.SubscribeAction.class,
              ninedof.proto.NinedofProto.SubscribeAction.Builder.class);
          sensorData.internalInit(descriptor.getExtensions().get(0));
          dataRequest.internalInit(descriptor.getExtensions().get(1));
          subscribeAction.internalInit(descriptor.getExtensions().get(2));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          amber.proto.AmberProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
