// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roboclaw.proto

package roboclaw.proto;

public final class RoboclawProto {
  private RoboclawProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(roboclaw.proto.RoboclawProto.motorsCommands);
    registry.add(roboclaw.proto.RoboclawProto.currentSpeedRequests);
    registry.add(roboclaw.proto.RoboclawProto.currentSpeeds);
    registry.add(roboclaw.proto.RoboclawProto.setPidConstantsRequests);
  }
  public interface MotorsCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 address = 1;
    boolean hasAddress();
    int getAddress();
    
    // optional int32 m1Speed = 2;
    boolean hasM1Speed();
    int getM1Speed();
    
    // optional uint32 m1Accel = 3;
    boolean hasM1Accel();
    int getM1Accel();
    
    // optional uint32 m1Distance = 4;
    boolean hasM1Distance();
    int getM1Distance();
    
    // optional bool m1Buffered = 5;
    boolean hasM1Buffered();
    boolean getM1Buffered();
    
    // optional int32 m2Speed = 6;
    boolean hasM2Speed();
    int getM2Speed();
    
    // optional uint32 m2Accel = 7;
    boolean hasM2Accel();
    int getM2Accel();
    
    // optional uint32 m2Distance = 8;
    boolean hasM2Distance();
    int getM2Distance();
    
    // optional bool m2Buffered = 9;
    boolean hasM2Buffered();
    boolean getM2Buffered();
  }
  public static final class MotorsCommand extends
      com.google.protobuf.GeneratedMessage
      implements MotorsCommandOrBuilder {
    // Use MotorsCommand.newBuilder() to construct.
    private MotorsCommand(Builder builder) {
      super(builder);
    }
    private MotorsCommand(boolean noInit) {}
    
    private static final MotorsCommand defaultInstance;
    public static MotorsCommand getDefaultInstance() {
      return defaultInstance;
    }
    
    public MotorsCommand getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_MotorsCommand_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_MotorsCommand_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 address = 1;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private int address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getAddress() {
      return address_;
    }
    
    // optional int32 m1Speed = 2;
    public static final int M1SPEED_FIELD_NUMBER = 2;
    private int m1Speed_;
    public boolean hasM1Speed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getM1Speed() {
      return m1Speed_;
    }
    
    // optional uint32 m1Accel = 3;
    public static final int M1ACCEL_FIELD_NUMBER = 3;
    private int m1Accel_;
    public boolean hasM1Accel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getM1Accel() {
      return m1Accel_;
    }
    
    // optional uint32 m1Distance = 4;
    public static final int M1DISTANCE_FIELD_NUMBER = 4;
    private int m1Distance_;
    public boolean hasM1Distance() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getM1Distance() {
      return m1Distance_;
    }
    
    // optional bool m1Buffered = 5;
    public static final int M1BUFFERED_FIELD_NUMBER = 5;
    private boolean m1Buffered_;
    public boolean hasM1Buffered() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getM1Buffered() {
      return m1Buffered_;
    }
    
    // optional int32 m2Speed = 6;
    public static final int M2SPEED_FIELD_NUMBER = 6;
    private int m2Speed_;
    public boolean hasM2Speed() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getM2Speed() {
      return m2Speed_;
    }
    
    // optional uint32 m2Accel = 7;
    public static final int M2ACCEL_FIELD_NUMBER = 7;
    private int m2Accel_;
    public boolean hasM2Accel() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getM2Accel() {
      return m2Accel_;
    }
    
    // optional uint32 m2Distance = 8;
    public static final int M2DISTANCE_FIELD_NUMBER = 8;
    private int m2Distance_;
    public boolean hasM2Distance() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getM2Distance() {
      return m2Distance_;
    }
    
    // optional bool m2Buffered = 9;
    public static final int M2BUFFERED_FIELD_NUMBER = 9;
    private boolean m2Buffered_;
    public boolean hasM2Buffered() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public boolean getM2Buffered() {
      return m2Buffered_;
    }
    
    private void initFields() {
      address_ = 0;
      m1Speed_ = 0;
      m1Accel_ = 0;
      m1Distance_ = 0;
      m1Buffered_ = false;
      m2Speed_ = 0;
      m2Accel_ = 0;
      m2Distance_ = 0;
      m2Buffered_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, address_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, m1Speed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, m1Accel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, m1Distance_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, m1Buffered_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, m2Speed_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, m2Accel_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(8, m2Distance_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(9, m2Buffered_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, address_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, m1Speed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, m1Accel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, m1Distance_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, m1Buffered_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, m2Speed_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, m2Accel_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, m2Distance_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, m2Buffered_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static roboclaw.proto.RoboclawProto.MotorsCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.MotorsCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.MotorsCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.MotorsCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.MotorsCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.MotorsCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.MotorsCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static roboclaw.proto.RoboclawProto.MotorsCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static roboclaw.proto.RoboclawProto.MotorsCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.MotorsCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(roboclaw.proto.RoboclawProto.MotorsCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements roboclaw.proto.RoboclawProto.MotorsCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_MotorsCommand_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_MotorsCommand_fieldAccessorTable;
      }
      
      // Construct using roboclaw.proto.RoboclawProto.MotorsCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        address_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        m1Speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        m1Accel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        m1Distance_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        m1Buffered_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        m2Speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        m2Accel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        m2Distance_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        m2Buffered_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return roboclaw.proto.RoboclawProto.MotorsCommand.getDescriptor();
      }
      
      public roboclaw.proto.RoboclawProto.MotorsCommand getDefaultInstanceForType() {
        return roboclaw.proto.RoboclawProto.MotorsCommand.getDefaultInstance();
      }
      
      public roboclaw.proto.RoboclawProto.MotorsCommand build() {
        roboclaw.proto.RoboclawProto.MotorsCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private roboclaw.proto.RoboclawProto.MotorsCommand buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        roboclaw.proto.RoboclawProto.MotorsCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public roboclaw.proto.RoboclawProto.MotorsCommand buildPartial() {
        roboclaw.proto.RoboclawProto.MotorsCommand result = new roboclaw.proto.RoboclawProto.MotorsCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.m1Speed_ = m1Speed_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.m1Accel_ = m1Accel_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.m1Distance_ = m1Distance_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.m1Buffered_ = m1Buffered_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.m2Speed_ = m2Speed_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.m2Accel_ = m2Accel_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.m2Distance_ = m2Distance_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.m2Buffered_ = m2Buffered_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof roboclaw.proto.RoboclawProto.MotorsCommand) {
          return mergeFrom((roboclaw.proto.RoboclawProto.MotorsCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(roboclaw.proto.RoboclawProto.MotorsCommand other) {
        if (other == roboclaw.proto.RoboclawProto.MotorsCommand.getDefaultInstance()) return this;
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasM1Speed()) {
          setM1Speed(other.getM1Speed());
        }
        if (other.hasM1Accel()) {
          setM1Accel(other.getM1Accel());
        }
        if (other.hasM1Distance()) {
          setM1Distance(other.getM1Distance());
        }
        if (other.hasM1Buffered()) {
          setM1Buffered(other.getM1Buffered());
        }
        if (other.hasM2Speed()) {
          setM2Speed(other.getM2Speed());
        }
        if (other.hasM2Accel()) {
          setM2Accel(other.getM2Accel());
        }
        if (other.hasM2Distance()) {
          setM2Distance(other.getM2Distance());
        }
        if (other.hasM2Buffered()) {
          setM2Buffered(other.getM2Buffered());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAddress()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              address_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              m1Speed_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              m1Accel_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              m1Distance_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              m1Buffered_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              m2Speed_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              m2Accel_ = input.readUInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              m2Distance_ = input.readUInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              m2Buffered_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 address = 1;
      private int address_ ;
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getAddress() {
        return address_;
      }
      public Builder setAddress(int value) {
        bitField0_ |= 0x00000001;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 m1Speed = 2;
      private int m1Speed_ ;
      public boolean hasM1Speed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getM1Speed() {
        return m1Speed_;
      }
      public Builder setM1Speed(int value) {
        bitField0_ |= 0x00000002;
        m1Speed_ = value;
        onChanged();
        return this;
      }
      public Builder clearM1Speed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        m1Speed_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 m1Accel = 3;
      private int m1Accel_ ;
      public boolean hasM1Accel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getM1Accel() {
        return m1Accel_;
      }
      public Builder setM1Accel(int value) {
        bitField0_ |= 0x00000004;
        m1Accel_ = value;
        onChanged();
        return this;
      }
      public Builder clearM1Accel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        m1Accel_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 m1Distance = 4;
      private int m1Distance_ ;
      public boolean hasM1Distance() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getM1Distance() {
        return m1Distance_;
      }
      public Builder setM1Distance(int value) {
        bitField0_ |= 0x00000008;
        m1Distance_ = value;
        onChanged();
        return this;
      }
      public Builder clearM1Distance() {
        bitField0_ = (bitField0_ & ~0x00000008);
        m1Distance_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool m1Buffered = 5;
      private boolean m1Buffered_ ;
      public boolean hasM1Buffered() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getM1Buffered() {
        return m1Buffered_;
      }
      public Builder setM1Buffered(boolean value) {
        bitField0_ |= 0x00000010;
        m1Buffered_ = value;
        onChanged();
        return this;
      }
      public Builder clearM1Buffered() {
        bitField0_ = (bitField0_ & ~0x00000010);
        m1Buffered_ = false;
        onChanged();
        return this;
      }
      
      // optional int32 m2Speed = 6;
      private int m2Speed_ ;
      public boolean hasM2Speed() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getM2Speed() {
        return m2Speed_;
      }
      public Builder setM2Speed(int value) {
        bitField0_ |= 0x00000020;
        m2Speed_ = value;
        onChanged();
        return this;
      }
      public Builder clearM2Speed() {
        bitField0_ = (bitField0_ & ~0x00000020);
        m2Speed_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 m2Accel = 7;
      private int m2Accel_ ;
      public boolean hasM2Accel() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getM2Accel() {
        return m2Accel_;
      }
      public Builder setM2Accel(int value) {
        bitField0_ |= 0x00000040;
        m2Accel_ = value;
        onChanged();
        return this;
      }
      public Builder clearM2Accel() {
        bitField0_ = (bitField0_ & ~0x00000040);
        m2Accel_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 m2Distance = 8;
      private int m2Distance_ ;
      public boolean hasM2Distance() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getM2Distance() {
        return m2Distance_;
      }
      public Builder setM2Distance(int value) {
        bitField0_ |= 0x00000080;
        m2Distance_ = value;
        onChanged();
        return this;
      }
      public Builder clearM2Distance() {
        bitField0_ = (bitField0_ & ~0x00000080);
        m2Distance_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool m2Buffered = 9;
      private boolean m2Buffered_ ;
      public boolean hasM2Buffered() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public boolean getM2Buffered() {
        return m2Buffered_;
      }
      public Builder setM2Buffered(boolean value) {
        bitField0_ |= 0x00000100;
        m2Buffered_ = value;
        onChanged();
        return this;
      }
      public Builder clearM2Buffered() {
        bitField0_ = (bitField0_ & ~0x00000100);
        m2Buffered_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:amber.roboclaw_proto.MotorsCommand)
    }
    
    static {
      defaultInstance = new MotorsCommand(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:amber.roboclaw_proto.MotorsCommand)
  }
  
  public interface SetPidConstantsRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 address = 1;
    boolean hasAddress();
    int getAddress();
    
    // required uint32 qpps = 2;
    boolean hasQpps();
    int getQpps();
    
    // required uint32 p = 3;
    boolean hasP();
    int getP();
    
    // required uint32 i = 4;
    boolean hasI();
    int getI();
    
    // required uint32 d = 5;
    boolean hasD();
    int getD();
  }
  public static final class SetPidConstantsRequest extends
      com.google.protobuf.GeneratedMessage
      implements SetPidConstantsRequestOrBuilder {
    // Use SetPidConstantsRequest.newBuilder() to construct.
    private SetPidConstantsRequest(Builder builder) {
      super(builder);
    }
    private SetPidConstantsRequest(boolean noInit) {}
    
    private static final SetPidConstantsRequest defaultInstance;
    public static SetPidConstantsRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public SetPidConstantsRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_SetPidConstantsRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_SetPidConstantsRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 address = 1;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private int address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getAddress() {
      return address_;
    }
    
    // required uint32 qpps = 2;
    public static final int QPPS_FIELD_NUMBER = 2;
    private int qpps_;
    public boolean hasQpps() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getQpps() {
      return qpps_;
    }
    
    // required uint32 p = 3;
    public static final int P_FIELD_NUMBER = 3;
    private int p_;
    public boolean hasP() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getP() {
      return p_;
    }
    
    // required uint32 i = 4;
    public static final int I_FIELD_NUMBER = 4;
    private int i_;
    public boolean hasI() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getI() {
      return i_;
    }
    
    // required uint32 d = 5;
    public static final int D_FIELD_NUMBER = 5;
    private int d_;
    public boolean hasD() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getD() {
      return d_;
    }
    
    private void initFields() {
      address_ = 0;
      qpps_ = 0;
      p_ = 0;
      i_ = 0;
      d_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQpps()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasP()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasI()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasD()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, address_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, qpps_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, p_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, i_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, d_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, address_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, qpps_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, p_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, i_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, d_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static roboclaw.proto.RoboclawProto.SetPidConstantsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.SetPidConstantsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.SetPidConstantsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.SetPidConstantsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.SetPidConstantsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.SetPidConstantsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.SetPidConstantsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static roboclaw.proto.RoboclawProto.SetPidConstantsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static roboclaw.proto.RoboclawProto.SetPidConstantsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.SetPidConstantsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(roboclaw.proto.RoboclawProto.SetPidConstantsRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements roboclaw.proto.RoboclawProto.SetPidConstantsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_SetPidConstantsRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_SetPidConstantsRequest_fieldAccessorTable;
      }
      
      // Construct using roboclaw.proto.RoboclawProto.SetPidConstantsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        address_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        qpps_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        p_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        i_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        d_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return roboclaw.proto.RoboclawProto.SetPidConstantsRequest.getDescriptor();
      }
      
      public roboclaw.proto.RoboclawProto.SetPidConstantsRequest getDefaultInstanceForType() {
        return roboclaw.proto.RoboclawProto.SetPidConstantsRequest.getDefaultInstance();
      }
      
      public roboclaw.proto.RoboclawProto.SetPidConstantsRequest build() {
        roboclaw.proto.RoboclawProto.SetPidConstantsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private roboclaw.proto.RoboclawProto.SetPidConstantsRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        roboclaw.proto.RoboclawProto.SetPidConstantsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public roboclaw.proto.RoboclawProto.SetPidConstantsRequest buildPartial() {
        roboclaw.proto.RoboclawProto.SetPidConstantsRequest result = new roboclaw.proto.RoboclawProto.SetPidConstantsRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.qpps_ = qpps_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.p_ = p_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.i_ = i_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.d_ = d_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof roboclaw.proto.RoboclawProto.SetPidConstantsRequest) {
          return mergeFrom((roboclaw.proto.RoboclawProto.SetPidConstantsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(roboclaw.proto.RoboclawProto.SetPidConstantsRequest other) {
        if (other == roboclaw.proto.RoboclawProto.SetPidConstantsRequest.getDefaultInstance()) return this;
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasQpps()) {
          setQpps(other.getQpps());
        }
        if (other.hasP()) {
          setP(other.getP());
        }
        if (other.hasI()) {
          setI(other.getI());
        }
        if (other.hasD()) {
          setD(other.getD());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAddress()) {
          
          return false;
        }
        if (!hasQpps()) {
          
          return false;
        }
        if (!hasP()) {
          
          return false;
        }
        if (!hasI()) {
          
          return false;
        }
        if (!hasD()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              address_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              qpps_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              p_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              i_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              d_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 address = 1;
      private int address_ ;
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getAddress() {
        return address_;
      }
      public Builder setAddress(int value) {
        bitField0_ |= 0x00000001;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 qpps = 2;
      private int qpps_ ;
      public boolean hasQpps() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getQpps() {
        return qpps_;
      }
      public Builder setQpps(int value) {
        bitField0_ |= 0x00000002;
        qpps_ = value;
        onChanged();
        return this;
      }
      public Builder clearQpps() {
        bitField0_ = (bitField0_ & ~0x00000002);
        qpps_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 p = 3;
      private int p_ ;
      public boolean hasP() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getP() {
        return p_;
      }
      public Builder setP(int value) {
        bitField0_ |= 0x00000004;
        p_ = value;
        onChanged();
        return this;
      }
      public Builder clearP() {
        bitField0_ = (bitField0_ & ~0x00000004);
        p_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 i = 4;
      private int i_ ;
      public boolean hasI() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getI() {
        return i_;
      }
      public Builder setI(int value) {
        bitField0_ |= 0x00000008;
        i_ = value;
        onChanged();
        return this;
      }
      public Builder clearI() {
        bitField0_ = (bitField0_ & ~0x00000008);
        i_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 d = 5;
      private int d_ ;
      public boolean hasD() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getD() {
        return d_;
      }
      public Builder setD(int value) {
        bitField0_ |= 0x00000010;
        d_ = value;
        onChanged();
        return this;
      }
      public Builder clearD() {
        bitField0_ = (bitField0_ & ~0x00000010);
        d_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:amber.roboclaw_proto.SetPidConstantsRequest)
    }
    
    static {
      defaultInstance = new SetPidConstantsRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:amber.roboclaw_proto.SetPidConstantsRequest)
  }
  
  public interface CurrentSpeedRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 address = 1;
    boolean hasAddress();
    int getAddress();
    
    // required bool m1Speed = 2 [default = false];
    boolean hasM1Speed();
    boolean getM1Speed();
    
    // required bool m2Speed = 3 [default = false];
    boolean hasM2Speed();
    boolean getM2Speed();
  }
  public static final class CurrentSpeedRequest extends
      com.google.protobuf.GeneratedMessage
      implements CurrentSpeedRequestOrBuilder {
    // Use CurrentSpeedRequest.newBuilder() to construct.
    private CurrentSpeedRequest(Builder builder) {
      super(builder);
    }
    private CurrentSpeedRequest(boolean noInit) {}
    
    private static final CurrentSpeedRequest defaultInstance;
    public static CurrentSpeedRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public CurrentSpeedRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_CurrentSpeedRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_CurrentSpeedRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 address = 1;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private int address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getAddress() {
      return address_;
    }
    
    // required bool m1Speed = 2 [default = false];
    public static final int M1SPEED_FIELD_NUMBER = 2;
    private boolean m1Speed_;
    public boolean hasM1Speed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getM1Speed() {
      return m1Speed_;
    }
    
    // required bool m2Speed = 3 [default = false];
    public static final int M2SPEED_FIELD_NUMBER = 3;
    private boolean m2Speed_;
    public boolean hasM2Speed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getM2Speed() {
      return m2Speed_;
    }
    
    private void initFields() {
      address_ = 0;
      m1Speed_ = false;
      m2Speed_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasM1Speed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasM2Speed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, address_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, m1Speed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, m2Speed_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, address_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, m1Speed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, m2Speed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static roboclaw.proto.RoboclawProto.CurrentSpeedRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeedRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeedRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeedRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeedRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeedRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeedRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeedRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeedRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeedRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(roboclaw.proto.RoboclawProto.CurrentSpeedRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements roboclaw.proto.RoboclawProto.CurrentSpeedRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_CurrentSpeedRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_CurrentSpeedRequest_fieldAccessorTable;
      }
      
      // Construct using roboclaw.proto.RoboclawProto.CurrentSpeedRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        address_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        m1Speed_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        m2Speed_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return roboclaw.proto.RoboclawProto.CurrentSpeedRequest.getDescriptor();
      }
      
      public roboclaw.proto.RoboclawProto.CurrentSpeedRequest getDefaultInstanceForType() {
        return roboclaw.proto.RoboclawProto.CurrentSpeedRequest.getDefaultInstance();
      }
      
      public roboclaw.proto.RoboclawProto.CurrentSpeedRequest build() {
        roboclaw.proto.RoboclawProto.CurrentSpeedRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private roboclaw.proto.RoboclawProto.CurrentSpeedRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        roboclaw.proto.RoboclawProto.CurrentSpeedRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public roboclaw.proto.RoboclawProto.CurrentSpeedRequest buildPartial() {
        roboclaw.proto.RoboclawProto.CurrentSpeedRequest result = new roboclaw.proto.RoboclawProto.CurrentSpeedRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.m1Speed_ = m1Speed_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.m2Speed_ = m2Speed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof roboclaw.proto.RoboclawProto.CurrentSpeedRequest) {
          return mergeFrom((roboclaw.proto.RoboclawProto.CurrentSpeedRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(roboclaw.proto.RoboclawProto.CurrentSpeedRequest other) {
        if (other == roboclaw.proto.RoboclawProto.CurrentSpeedRequest.getDefaultInstance()) return this;
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasM1Speed()) {
          setM1Speed(other.getM1Speed());
        }
        if (other.hasM2Speed()) {
          setM2Speed(other.getM2Speed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAddress()) {
          
          return false;
        }
        if (!hasM1Speed()) {
          
          return false;
        }
        if (!hasM2Speed()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              address_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              m1Speed_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              m2Speed_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 address = 1;
      private int address_ ;
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getAddress() {
        return address_;
      }
      public Builder setAddress(int value) {
        bitField0_ |= 0x00000001;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = 0;
        onChanged();
        return this;
      }
      
      // required bool m1Speed = 2 [default = false];
      private boolean m1Speed_ ;
      public boolean hasM1Speed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getM1Speed() {
        return m1Speed_;
      }
      public Builder setM1Speed(boolean value) {
        bitField0_ |= 0x00000002;
        m1Speed_ = value;
        onChanged();
        return this;
      }
      public Builder clearM1Speed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        m1Speed_ = false;
        onChanged();
        return this;
      }
      
      // required bool m2Speed = 3 [default = false];
      private boolean m2Speed_ ;
      public boolean hasM2Speed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getM2Speed() {
        return m2Speed_;
      }
      public Builder setM2Speed(boolean value) {
        bitField0_ |= 0x00000004;
        m2Speed_ = value;
        onChanged();
        return this;
      }
      public Builder clearM2Speed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        m2Speed_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:amber.roboclaw_proto.CurrentSpeedRequest)
    }
    
    static {
      defaultInstance = new CurrentSpeedRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:amber.roboclaw_proto.CurrentSpeedRequest)
  }
  
  public interface CurrentSpeedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 address = 1;
    boolean hasAddress();
    int getAddress();
    
    // optional int32 m1Speed = 2;
    boolean hasM1Speed();
    int getM1Speed();
    
    // optional int32 m2Speed = 3;
    boolean hasM2Speed();
    int getM2Speed();
  }
  public static final class CurrentSpeed extends
      com.google.protobuf.GeneratedMessage
      implements CurrentSpeedOrBuilder {
    // Use CurrentSpeed.newBuilder() to construct.
    private CurrentSpeed(Builder builder) {
      super(builder);
    }
    private CurrentSpeed(boolean noInit) {}
    
    private static final CurrentSpeed defaultInstance;
    public static CurrentSpeed getDefaultInstance() {
      return defaultInstance;
    }
    
    public CurrentSpeed getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_CurrentSpeed_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_CurrentSpeed_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 address = 1;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private int address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getAddress() {
      return address_;
    }
    
    // optional int32 m1Speed = 2;
    public static final int M1SPEED_FIELD_NUMBER = 2;
    private int m1Speed_;
    public boolean hasM1Speed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getM1Speed() {
      return m1Speed_;
    }
    
    // optional int32 m2Speed = 3;
    public static final int M2SPEED_FIELD_NUMBER = 3;
    private int m2Speed_;
    public boolean hasM2Speed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getM2Speed() {
      return m2Speed_;
    }
    
    private void initFields() {
      address_ = 0;
      m1Speed_ = 0;
      m2Speed_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, address_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, m1Speed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, m2Speed_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, address_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, m1Speed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, m2Speed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static roboclaw.proto.RoboclawProto.CurrentSpeed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeed parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeed parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static roboclaw.proto.RoboclawProto.CurrentSpeed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(roboclaw.proto.RoboclawProto.CurrentSpeed prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements roboclaw.proto.RoboclawProto.CurrentSpeedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_CurrentSpeed_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return roboclaw.proto.RoboclawProto.internal_static_amber_roboclaw_proto_CurrentSpeed_fieldAccessorTable;
      }
      
      // Construct using roboclaw.proto.RoboclawProto.CurrentSpeed.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        address_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        m1Speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        m2Speed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return roboclaw.proto.RoboclawProto.CurrentSpeed.getDescriptor();
      }
      
      public roboclaw.proto.RoboclawProto.CurrentSpeed getDefaultInstanceForType() {
        return roboclaw.proto.RoboclawProto.CurrentSpeed.getDefaultInstance();
      }
      
      public roboclaw.proto.RoboclawProto.CurrentSpeed build() {
        roboclaw.proto.RoboclawProto.CurrentSpeed result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private roboclaw.proto.RoboclawProto.CurrentSpeed buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        roboclaw.proto.RoboclawProto.CurrentSpeed result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public roboclaw.proto.RoboclawProto.CurrentSpeed buildPartial() {
        roboclaw.proto.RoboclawProto.CurrentSpeed result = new roboclaw.proto.RoboclawProto.CurrentSpeed(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.m1Speed_ = m1Speed_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.m2Speed_ = m2Speed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof roboclaw.proto.RoboclawProto.CurrentSpeed) {
          return mergeFrom((roboclaw.proto.RoboclawProto.CurrentSpeed)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(roboclaw.proto.RoboclawProto.CurrentSpeed other) {
        if (other == roboclaw.proto.RoboclawProto.CurrentSpeed.getDefaultInstance()) return this;
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasM1Speed()) {
          setM1Speed(other.getM1Speed());
        }
        if (other.hasM2Speed()) {
          setM2Speed(other.getM2Speed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAddress()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              address_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              m1Speed_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              m2Speed_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 address = 1;
      private int address_ ;
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getAddress() {
        return address_;
      }
      public Builder setAddress(int value) {
        bitField0_ |= 0x00000001;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 m1Speed = 2;
      private int m1Speed_ ;
      public boolean hasM1Speed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getM1Speed() {
        return m1Speed_;
      }
      public Builder setM1Speed(int value) {
        bitField0_ |= 0x00000002;
        m1Speed_ = value;
        onChanged();
        return this;
      }
      public Builder clearM1Speed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        m1Speed_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 m2Speed = 3;
      private int m2Speed_ ;
      public boolean hasM2Speed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getM2Speed() {
        return m2Speed_;
      }
      public Builder setM2Speed(int value) {
        bitField0_ |= 0x00000004;
        m2Speed_ = value;
        onChanged();
        return this;
      }
      public Builder clearM2Speed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        m2Speed_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:amber.roboclaw_proto.CurrentSpeed)
    }
    
    static {
      defaultInstance = new CurrentSpeed(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:amber.roboclaw_proto.CurrentSpeed)
  }
  
  public static final int MOTORSCOMMANDS_FIELD_NUMBER = 10;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      amber.proto.AmberProto.DriverMsg,
      java.util.List<roboclaw.proto.RoboclawProto.MotorsCommand>> motorsCommands = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        roboclaw.proto.RoboclawProto.MotorsCommand.class,
        roboclaw.proto.RoboclawProto.MotorsCommand.getDefaultInstance());
  public static final int CURRENTSPEEDREQUESTS_FIELD_NUMBER = 11;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      amber.proto.AmberProto.DriverMsg,
      java.util.List<roboclaw.proto.RoboclawProto.CurrentSpeedRequest>> currentSpeedRequests = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        roboclaw.proto.RoboclawProto.CurrentSpeedRequest.class,
        roboclaw.proto.RoboclawProto.CurrentSpeedRequest.getDefaultInstance());
  public static final int CURRENTSPEEDS_FIELD_NUMBER = 12;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      amber.proto.AmberProto.DriverMsg,
      java.util.List<roboclaw.proto.RoboclawProto.CurrentSpeed>> currentSpeeds = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        roboclaw.proto.RoboclawProto.CurrentSpeed.class,
        roboclaw.proto.RoboclawProto.CurrentSpeed.getDefaultInstance());
  public static final int SETPIDCONSTANTSREQUESTS_FIELD_NUMBER = 13;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      amber.proto.AmberProto.DriverMsg,
      java.util.List<roboclaw.proto.RoboclawProto.SetPidConstantsRequest>> setPidConstantsRequests = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        roboclaw.proto.RoboclawProto.SetPidConstantsRequest.class,
        roboclaw.proto.RoboclawProto.SetPidConstantsRequest.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_roboclaw_proto_MotorsCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_roboclaw_proto_MotorsCommand_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_roboclaw_proto_SetPidConstantsRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_roboclaw_proto_SetPidConstantsRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_roboclaw_proto_CurrentSpeedRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_roboclaw_proto_CurrentSpeedRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_amber_roboclaw_proto_CurrentSpeed_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_amber_roboclaw_proto_CurrentSpeed_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016roboclaw.proto\022\024amber.roboclaw_proto\032\017" +
      "drivermsg.proto\"\264\001\n\rMotorsCommand\022\017\n\007add" +
      "ress\030\001 \002(\r\022\017\n\007m1Speed\030\002 \001(\005\022\017\n\007m1Accel\030\003" +
      " \001(\r\022\022\n\nm1Distance\030\004 \001(\r\022\022\n\nm1Buffered\030\005" +
      " \001(\010\022\017\n\007m2Speed\030\006 \001(\005\022\017\n\007m2Accel\030\007 \001(\r\022\022" +
      "\n\nm2Distance\030\010 \001(\r\022\022\n\nm2Buffered\030\t \001(\010\"X" +
      "\n\026SetPidConstantsRequest\022\017\n\007address\030\001 \002(" +
      "\r\022\014\n\004qpps\030\002 \002(\r\022\t\n\001p\030\003 \002(\r\022\t\n\001i\030\004 \002(\r\022\t\n" +
      "\001d\030\005 \002(\r\"V\n\023CurrentSpeedRequest\022\017\n\007addre" +
      "ss\030\001 \002(\r\022\026\n\007m1Speed\030\002 \002(\010:\005false\022\026\n\007m2Sp",
      "eed\030\003 \002(\010:\005false\"A\n\014CurrentSpeed\022\017\n\007addr" +
      "ess\030\001 \002(\r\022\017\n\007m1Speed\030\002 \001(\005\022\017\n\007m2Speed\030\003 " +
      "\001(\005:M\n\016motorsCommands\022\020.amber.DriverMsg\030" +
      "\n \003(\0132#.amber.roboclaw_proto.MotorsComma" +
      "nd:Y\n\024currentSpeedRequests\022\020.amber.Drive" +
      "rMsg\030\013 \003(\0132).amber.roboclaw_proto.Curren" +
      "tSpeedRequest:K\n\rcurrentSpeeds\022\020.amber.D" +
      "riverMsg\030\014 \003(\0132\".amber.roboclaw_proto.Cu" +
      "rrentSpeed:_\n\027setPidConstantsRequests\022\020." +
      "amber.DriverMsg\030\r \003(\0132,.amber.roboclaw_p",
      "roto.SetPidConstantsRequestB\037\n\016roboclaw." +
      "protoB\rRoboclawProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_amber_roboclaw_proto_MotorsCommand_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_amber_roboclaw_proto_MotorsCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_roboclaw_proto_MotorsCommand_descriptor,
              new java.lang.String[] { "Address", "M1Speed", "M1Accel", "M1Distance", "M1Buffered", "M2Speed", "M2Accel", "M2Distance", "M2Buffered", },
              roboclaw.proto.RoboclawProto.MotorsCommand.class,
              roboclaw.proto.RoboclawProto.MotorsCommand.Builder.class);
          internal_static_amber_roboclaw_proto_SetPidConstantsRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_amber_roboclaw_proto_SetPidConstantsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_roboclaw_proto_SetPidConstantsRequest_descriptor,
              new java.lang.String[] { "Address", "Qpps", "P", "I", "D", },
              roboclaw.proto.RoboclawProto.SetPidConstantsRequest.class,
              roboclaw.proto.RoboclawProto.SetPidConstantsRequest.Builder.class);
          internal_static_amber_roboclaw_proto_CurrentSpeedRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_amber_roboclaw_proto_CurrentSpeedRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_roboclaw_proto_CurrentSpeedRequest_descriptor,
              new java.lang.String[] { "Address", "M1Speed", "M2Speed", },
              roboclaw.proto.RoboclawProto.CurrentSpeedRequest.class,
              roboclaw.proto.RoboclawProto.CurrentSpeedRequest.Builder.class);
          internal_static_amber_roboclaw_proto_CurrentSpeed_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_amber_roboclaw_proto_CurrentSpeed_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_amber_roboclaw_proto_CurrentSpeed_descriptor,
              new java.lang.String[] { "Address", "M1Speed", "M2Speed", },
              roboclaw.proto.RoboclawProto.CurrentSpeed.class,
              roboclaw.proto.RoboclawProto.CurrentSpeed.Builder.class);
          motorsCommands.internalInit(descriptor.getExtensions().get(0));
          currentSpeedRequests.internalInit(descriptor.getExtensions().get(1));
          currentSpeeds.internalInit(descriptor.getExtensions().get(2));
          setPidConstantsRequests.internalInit(descriptor.getExtensions().get(3));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          amber.proto.AmberProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
